/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appinfoenergia;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.Control;
import model.Perfil;
import modelDAO.ControlDAO;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Jesus Enrique
 */
public class home extends javax.swing.JFrame {

    public static Perfil perfil;
    DefaultTableModel model;
    String[] meses = {"enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "setiembre", "octubre", "noviembre", "diciembre"};
    String[] años = {"2020", "2021", "2022"};
    ControlDAO cdao;

    /**
     * Creates new form home
     */
    public home() {
        cdao = new ControlDAO();
        this.setUndecorated(true);
        initComponents();

        periodoCombo.setModel(new DefaultComboBoxModel<>(meses));
        anioCombo.setModel(new DefaultComboBoxModel<>(años));
        cargarArtefatos();
        perfil = bienvenida.perfil;
        lblBienvenido.setText("Control de" + bienvenida.sesion.getUserSesion().getNombres());
    }

    private void cargarArtefatos() {
        model = new DefaultTableModel();
        model.addColumn("Artefacto");
        model.addColumn("Cantidad");
        model.addColumn("Tiempo de uso");
        model.addColumn("Kv/h ");
        model.addColumn("Días del mes");
        model.addColumn("Periodo");
        controlTable.setModel(model);
        ArrayList<Control> controles = cdao.perfil_control_all(bienvenida.sesion.getUserSesion().getCodigo_perfil());
        controles.forEach((c) -> {
            String[] ctrl = new String[6];
            ctrl[0] = c.getNombre_artefacto();
            ctrl[1] = c.getCantidad() + "";
            ctrl[2] = c.getTiempo_uso() + "";
            ctrl[3] = c.getKv() + "";
            ctrl[4] = c.getDia_uso() + "";
            ctrl[5] = c.getPeriodo() + "";
            model.addRow(ctrl);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        periodoCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        anioCombo = new javax.swing.JComboBox<>();
        agregarEquipoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        reporteSolesPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        acercaDePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        reporteKvPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cerrarSesionPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lblBienvenido = new javax.swing.JLabel();
        filtrarPanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        controlTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(21, 67, 96));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(245, 246, 247));
        jLabel2.setText("Periodo:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(245, 246, 247));
        jLabel3.setText("Año:");

        agregarEquipoPanel.setBackground(new java.awt.Color(19, 141, 117));
        agregarEquipoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarEquipoPanelMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 246, 247));
        jLabel1.setText("Agregar un nuevo equipo");

        javax.swing.GroupLayout agregarEquipoPanelLayout = new javax.swing.GroupLayout(agregarEquipoPanel);
        agregarEquipoPanel.setLayout(agregarEquipoPanelLayout);
        agregarEquipoPanelLayout.setHorizontalGroup(
            agregarEquipoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarEquipoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        agregarEquipoPanelLayout.setVerticalGroup(
            agregarEquipoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarEquipoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        reporteSolesPanel.setBackground(new java.awt.Color(19, 141, 117));
        reporteSolesPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reporteSolesPanelMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(245, 246, 247));
        jLabel6.setText("Reporte S/.");

        javax.swing.GroupLayout reporteSolesPanelLayout = new javax.swing.GroupLayout(reporteSolesPanel);
        reporteSolesPanel.setLayout(reporteSolesPanelLayout);
        reporteSolesPanelLayout.setHorizontalGroup(
            reporteSolesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reporteSolesPanelLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(39, 39, 39))
        );
        reporteSolesPanelLayout.setVerticalGroup(
            reporteSolesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteSolesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        acercaDePanel.setBackground(new java.awt.Color(19, 141, 117));
        acercaDePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acercaDePanelMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(245, 246, 247));
        jLabel7.setText("Acerca de");

        javax.swing.GroupLayout acercaDePanelLayout = new javax.swing.GroupLayout(acercaDePanel);
        acercaDePanel.setLayout(acercaDePanelLayout);
        acercaDePanelLayout.setHorizontalGroup(
            acercaDePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acercaDePanelLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(39, 39, 39))
        );
        acercaDePanelLayout.setVerticalGroup(
            acercaDePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acercaDePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        reporteKvPanel.setBackground(new java.awt.Color(19, 141, 117));
        reporteKvPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reporteKvPanelMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(245, 246, 247));
        jLabel17.setText("Report Kv-h");

        javax.swing.GroupLayout reporteKvPanelLayout = new javax.swing.GroupLayout(reporteKvPanel);
        reporteKvPanel.setLayout(reporteKvPanelLayout);
        reporteKvPanelLayout.setHorizontalGroup(
            reporteKvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reporteKvPanelLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(30, 30, 30))
        );
        reporteKvPanelLayout.setVerticalGroup(
            reporteKvPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteKvPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cerrarSesionPanel.setBackground(new java.awt.Color(19, 141, 117));
        cerrarSesionPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionPanelMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(245, 246, 247));
        jLabel18.setText("Cerrar Sesión");

        javax.swing.GroupLayout cerrarSesionPanelLayout = new javax.swing.GroupLayout(cerrarSesionPanel);
        cerrarSesionPanel.setLayout(cerrarSesionPanelLayout);
        cerrarSesionPanelLayout.setHorizontalGroup(
            cerrarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cerrarSesionPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel18)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        cerrarSesionPanelLayout.setVerticalGroup(
            cerrarSesionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cerrarSesionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblBienvenido.setFont(new java.awt.Font("Ubuntu", 0, 30)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(245, 246, 247));
        lblBienvenido.setText("jLabel19");

        filtrarPanel.setBackground(new java.awt.Color(245, 176, 65));
        filtrarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filtrarPanelMouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(245, 246, 247));
        jLabel20.setText("Filtrar");

        javax.swing.GroupLayout filtrarPanelLayout = new javax.swing.GroupLayout(filtrarPanel);
        filtrarPanel.setLayout(filtrarPanelLayout);
        filtrarPanelLayout.setHorizontalGroup(
            filtrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filtrarPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel20)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        filtrarPanelLayout.setVerticalGroup(
            filtrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filtrarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("X");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jPanel19.setBackground(new java.awt.Color(231, 76, 60));
        jPanel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel19MouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(245, 246, 247));
        jLabel21.setText("Eliminar filtro");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel21)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        controlTable.setForeground(new java.awt.Color(0, 0, 0));
        controlTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Artefacto Eléctrico", "Cantidad", "Tiempo de Uso", "Kv-h", "Dias al Mes", "Consumo Kv-h", "Consumo Mensual S/"
            }
        ));
        jScrollPane1.setViewportView(controlTable);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 869, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        jLabel4.setText("Total:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(agregarEquipoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reporteSolesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reporteKvPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(acercaDePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cerrarSesionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(lblBienvenido)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19))
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(periodoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(anioCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(filtrarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblBienvenido))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel19)))
                .addGap(37, 37, 37)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reporteKvPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agregarEquipoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reporteSolesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(acercaDePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cerrarSesionPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(anioCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(periodoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(filtrarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void agregarEquipoPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarEquipoPanelMouseClicked
        // TODO add your handling code here:
        nuevoEquipo nEquipo = new nuevoEquipo();
        nEquipo.setVisible(true);

        dispose();

    }//GEN-LAST:event_agregarEquipoPanelMouseClicked

    private void reporteSolesPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteSolesPanelMouseClicked
        // TODO add your handling code here:
        // Fuente de Datos
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (int i = 0; i < meses.length; i++) {            
            dataset.setValue(cdao.total_por_mes(bienvenida.sesion.getUserSesion().getCodigo_perfil(), i+1)*bienvenida.sesion.getUserSesion().getCosto_kv(), "Soles", meses[i]);
        }
        // dataset.setValue(5, "Hombres", "Marzo");
        JFreeChart chart = ChartFactory.createBarChart3D("Consumo Mensual S/ ", "Mes", "",
                dataset, PlotOrientation.VERTICAL, true, true, false);
        chart.setBackgroundPaint(Color.white);
        chart.getTitle().setPaint(Color.black);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.blue);

        // Mostrar Grafico
        ChartFrame frame = new ChartFrame("Reporte en soles", chart);
        frame.setBounds(380, 180, 0, 0);
        frame.pack();
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_reporteSolesPanelMouseClicked

    private void acercaDePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acercaDePanelMouseClicked
        // TODO add your handling code here:
        acercaDe acercaDee = new acercaDe();
        acercaDee.setVisible(true);

    }//GEN-LAST:event_acercaDePanelMouseClicked

    private void reporteKvPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporteKvPanelMouseClicked
        // TODO add your handling code here:
        // Fuente de Datos
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (int i = 0; i < meses.length; i++) {
            dataset.setValue(cdao.total_por_mes(bienvenida.sesion.getUserSesion().getCodigo_perfil(), i+1), "Kilovatios-hora    ", meses[i]);
        }
        // Creando el Grafico
        JFreeChart chart = ChartFactory.createBarChart3D("Consumo Mensual Kilovatio-hora", "Mes", "",
                dataset, PlotOrientation.VERTICAL, true, true, false);
        chart.setBackgroundPaint(Color.white);
        chart.getTitle().setPaint(Color.black);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.blue);

        // Mostrar Grafico
        ChartFrame frame = new ChartFrame("Reporte Kv", chart);
        frame.setBounds(380, 180, 0, 0);

        frame.pack();
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_reporteKvPanelMouseClicked

    private void cerrarSesionPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionPanelMouseClicked
        // TODO add your handling code here:
        bienvenida.sesion.cerrarSesion();
        bienvenida bvnd = new bienvenida();
        bvnd.setVisible(true);

        dispose();
    }//GEN-LAST:event_cerrarSesionPanelMouseClicked

    private void filtrarPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filtrarPanelMouseClicked
        // TODO add your handling code here:
        model = new DefaultTableModel();
        model.addColumn("Artefacto");
        model.addColumn("Cantidad");
        model.addColumn("Tiempo de uso");
        model.addColumn("Kv/h ");
        model.addColumn("Días del mes");
        model.addColumn("Periodo");
        controlTable.setModel(model);

        int mes = periodoCombo.getSelectedIndex() + 1;
        String anio = (String) anioCombo.getSelectedItem();

        ArrayList<Control> controles;
        controles = cdao.perfil_control_por_mes(bienvenida.sesion.getUserSesion().getCodigo_perfil(), anio, mes + "");
        controles.forEach((c) -> {
            String[] ctrl = new String[6];
            ctrl[0] = c.getNombre_artefacto();
            ctrl[1] = c.getCantidad() + "";
            ctrl[2] = c.getTiempo_uso() + "";
            ctrl[3] = c.getKv() + "";
            ctrl[4] = c.getDia_uso() + "";
            ctrl[5] = c.getPeriodo() + "";
            model.addRow(ctrl);
        });
        
        totalLabel.setText(cdao.total_por_mes(bienvenida.sesion.getUserSesion().getCodigo_perfil(), mes)+"");
    }//GEN-LAST:event_filtrarPanelMouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jPanel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19MouseClicked
        // TODO add your handling code here:
        model = new DefaultTableModel();
        model.addColumn("Artefacto");
        model.addColumn("Cantidad");
        model.addColumn("Tiempo de uso");
        model.addColumn("Kv/h ");
        model.addColumn("Días del mes");
        model.addColumn("Periodo");
        controlTable.setModel(model);

        ArrayList<Control> controles = cdao.perfil_control_all(bienvenida.sesion.getUserSesion().getCodigo_perfil());
        controles.forEach((c) -> {
            String[] ctrl = new String[6];
            ctrl[0] = c.getNombre_artefacto();
            ctrl[1] = c.getCantidad() + "";
            ctrl[2] = c.getTiempo_uso() + "";
            ctrl[3] = c.getKv() + "";
            ctrl[4] = c.getDia_uso() + "";
            ctrl[5] = c.getPeriodo() + "";
            model.addRow(ctrl);
        });
        totalLabel.setText("");
    }//GEN-LAST:event_jPanel19MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel acercaDePanel;
    private javax.swing.JPanel agregarEquipoPanel;
    private javax.swing.JComboBox<String> anioCombo;
    private javax.swing.JPanel cerrarSesionPanel;
    private javax.swing.JTable controlTable;
    private javax.swing.JPanel filtrarPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JComboBox<String> periodoCombo;
    private javax.swing.JPanel reporteKvPanel;
    private javax.swing.JPanel reporteSolesPanel;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
